function radar_funs = load_radar_functions
%     radar_funs = LoadRadarFunctions
%
%    UNCLASSIFIED     UNCLASSIFIED     UNCLASSIFIED     UNCLASSIFIED     
%
%   DESCRIPTION
%        This function creates the structure radar_funs.  This represents
%   the radar function names and values used in the simulation.
%
%   Input:
%        none
%
%   Output:
%        radar_funs  --  A structure containing the names and values of
%                          the radar function values
%           None
%
%   Required Functions:
%        None
%

%Note, these also function as an index into the array map_tp_sap_1109
radar_funs = struct( ...
   'Unspecified', 0, ...
   'Rtcp', 1, ...
   'SearchNoiseMeas', 2, ...
   'CalibrationNoiseMeas', 3, ...
   'InterceptorSupport', 4, ...
   'Verify', 5, ...
   'TIPulsePair', 6, ...
   'InitialTM', 7, ...
   'ObjectTrack', 8, ...
   'Discrimination', 9, ...
   'Reserved_1', 10, ...
   'Imaging', 11, ...
   'HitAssessment', 12, ...
   'SignatureDataCollection', 13, ...
   'Calibration', 14, ...
   'SelfCuedSearch', 15, ...
   'CuedSearch', 16, ...
   'ReacquisitionSearch', 17, ...
   'SatelliteSearch', 18, ...
   'BalloonSearch', 19, ...
   'InterceptorBoosterSearch', 20, ...
   'InterceptorKVSearch', 21, ...
   'NarrowBandSearch', 22, ...
   'FBR', 23);

return
%    UNCLASSIFIED     UNCLASSIFIED     UNCLASSIFIED     UNCLASSIFIED     
