% butdraw.m  GENERATE BUTTONS: DRAW DIGITAL & ANALOG FILTER REALIZATIONS
%   
%                 Drawing Filter Realizations
%   
%   Authors: Miroslav D. Lutovac, Dejan V. Tosic, 1999/02/21
%   lutovac@iritel.bg.ac.yu    http://galeb.etf.bg.ac.yu/~lutovac/
%   tosic@galeb.etf.bg.ac.yu   http://www.rcub.bg.ac.yu/~tosicde/
%   Copyright (c) 1999-2000 by Lutovac & Tosic
%   $Revision: 1.21 $  $Date: 2000/10/03 13:45$
%   
%   References:
%   Miroslav D. Lutovac, Dejan V. Tosic, Brian L. Evans
%        Filter Design for Signal Processing
%           Using MATLAB and Mathematica
%        Prentice Hall - ISBN 0-201-36130-2 
%         http://www.prenhall.com/lutovac
%   
                         
% This file is part of DrawFilt toolbox for MATLAB.
% Refer to the file LICENSE.TXT for full details.
%                        
% DrawFilt version 2.1, Copyright (c) 1999-2000 M. Lutovac and D. Tosic
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; see LICENSE.TXT for details.
%                       
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%                       
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc.,  59 Temple Place,  Suite 330,  Boston,
% MA  02111-1307  USA,  http://www.fsf.org/
                 
clc

if exist('editString') == 0
  editString = [0 1];
end
if exist('matrixEdel') == 0
  matrixEdel = [];
end

dc = 'b';
matrixEnew = ['                                                             '];
rdr = 'clf;[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);bdrwredr(x0,y0,dx,ds,F,Nx,Ny,matrixE,dc);butdraw';
ddfr =  ['''VIEW realization from auxfilt.m''' ',''NumberTitle'', ''off'''];
ddfre=  ['''Make EPS file from auxfilt.m''' ',''NumberTitle'', ''off'''];
ddfrx=  ['''EXAMPLE from exampleX.m''' ',''NumberTitle'', ''off'''];
ddfr1=  ['''EXAMPLE from example1.m''' ',''NumberTitle'', ''off'''];
ddfr2=  ['''EXAMPLE from example2.m''' ',''NumberTitle'', ''off'''];
ddfr3=  ['''EXAMPLE from example3.m''' ',''NumberTitle'', ''off'''];
ddfr4=  ['''EXAMPLE from example4.m''' ',''NumberTitle'', ''off'''];
trdr = ['if txtst==1;' rdr ';txtst=0; end;'];


if  editString(1) == 0
  
uvADDER = uicontrol('String', 'Adder', 'Units', 'normalized' ...
     , 'Position', [0.01 0.940 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwadd(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvMULT = uicontrol('String', 'Mult', 'Units', 'normalized' ...
     , 'Position', [0.01 0.885 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwmult(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvDELAY = uicontrol('String', 'Delay', 'Units', 'normalized' ...
     , 'Position', [0.01 0.830 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwdel(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvUP = uicontrol('String', 'UP', 'Units', 'normalized' ...
     , 'Position', [0.01 0.775 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwupsa(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvDOWN = uicontrol('String', 'down', 'Units', 'normalized' ...
     , 'Position', [0.01 0.72 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwdown(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvLINE = uicontrol('String', 'LINE', 'Units', 'normalized' ...
     , 'Position', [0.01 0.665 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwline(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvLINEHV = uicontrol('String', '__I', 'Units', 'normalized' ...
     , 'Position', [0.01 0.61 0.045 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwlhv(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvLINEVH= uicontrol('String', 'I__', 'Units', 'normalized' ...
     , 'Position', [0.01 0.555 0.045 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwlvh(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvARROW = uicontrol('String', '>', 'Units', 'normalized' ...
     , 'Position', [0.055 0.61 0.04 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwarrw(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvIN = uicontrol('String', 'In', 'Units', 'normalized' ...
     , 'Position', [0.055 0.555 0.04 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwin(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvOUT = uicontrol('String', 'Out', 'Units', 'normalized' ...
     , 'Position', [0.01 0.50 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwout(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvNODE = uicontrol('String', 'NODE', 'Units', 'normalized' ...
   , 'Position', [0.01 0.445 0.08 0.05], 'CallBack', ...
   [trdr '[xs,matrixE]=bdrwnode(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvTEXT = uicontrol('String', 'TEXT', 'Units', 'normalized' ...
     , 'Position', [0.01 0.390 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwtext(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvBLOCK = uicontrol('String', 'Block', 'Units', 'normalized' ...
     , 'Position', [0.01 0.335 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwblo(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uv4tBLOCK = uicontrol('String', 'Block 4', 'Units', 'normalized' ...
     , 'Position', [0.01 0.285 0.085 0.045], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrw4tbl(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
% ----------------------------------------------------------------------------------

uvCC = uicontrol('String', 'CC', 'Units', 'normalized' ...
     , 'Position', [0.01 0.230 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwcc(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvOTA = uicontrol('String', 'OTA', 'Units', 'normalized' ...
     , 'Position', [0.01 0.175 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwota(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvOPAMPA = uicontrol('String', 'OpAmp', 'Units', 'normalized' ...
     , 'Position', [0.01 0.120 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwopam(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvGRND = uicontrol('String', 'GRND', 'Units', 'normalized' ...
     , 'Position', [0.01 0.065 0.08 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwgrnd(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
% ----------------------------------------------------------------

uvR = uicontrol('String', 'R', 'Units', 'normalized' ...
     , 'Position', [0.01 0.01 0.04 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwres(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvC = uicontrol('String', 'C', 'Units', 'normalized' ...
     , 'Position', [0.055 0.01 0.04 0.05], 'CallBack', ...
  [trdr '[xs,matrixE]=bdrwcap(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvL = uicontrol('String', 'L', 'Units', 'normalized' ...
     , 'Position', [0.1 0.01 0.04 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwlnd(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvZ = uicontrol('String', 'Z', 'Units', 'normalized' ...
     , 'Position', [0.145 0.01 0.04 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwimp(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

uvVS = uicontrol('String', '(V)', 'Units', 'normalized' ...
     , 'Position', [0.19 0.01 0.05 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwvs(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvCS = uicontrol('String', '(I)', 'Units', 'normalized' ...
     , 'Position', [0.245 0.01 0.05 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwcs(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvCVS = uicontrol('String', '<V>', 'Units', 'normalized' ...
     , 'Position', [0.3 0.01 0.05 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwcvs(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);
  
uvCCS = uicontrol('String', '<I>', 'Units', 'normalized' ...
     , 'Position', [0.355 0.01 0.05 0.05], 'CallBack', ...
     [trdr '[xs,matrixE]=bdrwccs(matrixE,x,y,ds,F,dc); title(''CLICK a button'')']);

% ----------------------------------------------------------------------------------

uiINFO= uicontrol('String', 'info', 'Units', 'normalized' ...
     , 'Position', [0.82 0.94 0.08 0.05] ...
     , 'CallBack', 'clf,bdrwinfo(dx,Ny);butdraw;txtst=1;');
  
uiCLOSE = uicontrol('String', 'close', 'Units', 'normalized' ...
   , 'Position', [0.92 0.94 0.08 0.05], 'CallBack', 'close');

% ----------------------------------------------------------------------------------

uiNEW = uicontrol('String', 'NEW', 'Units', 'normalized' ...
     , 'Position', [0.92 0.80 0.08 0.05], 'CallBack', ...
     'clf;[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);matrixE=matrixEnew;butdraw');
  
uiOPENFROM = uicontrol('String', 'OPEN', 'Units', 'normalized', ...
        'Position', [0.92 0.74 0.08 0.05], 'CallBack', ...
        ['clf;[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);' ...
        'matrixE=bdrwopen(x0,y0,dx,ds,F,Nx,Ny,matrixE); ' ...
        'bdrwredr(x0,y0,dx,ds,F,Nx,Ny,matrixE,dc);butdraw']);

callbackStr = [';[matrixE,editString]=bdrwedit(x0,y0,dx,ds,F,Nx,Ny,matrixE,editString);'];
callbackStr = [callbackStr 'editstr;'];
callbackStr = [callbackStr 'figure(1);'];
callbackStr = [callbackStr 'clf;[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);'];
callbackStr = [callbackStr 'bdrwredr(x0,y0,dx,ds,F,Nx,Ny,matrixE,dc);'];
callbackStr = [callbackStr 'butdraw;'];
callbackStr = [callbackStr 'set(gcf,''DefaultTextColor'',''r'');'];
callbackStr = [callbackStr 'dc = ''r'';eval(matrixE(editString(2),:)); '];
callbackStr = [callbackStr 'title(''GO TO Edit window'');'];
callbackStr = [callbackStr 'set(gcf,''DefaultTextColor'',''k''); '];
callbackStr = [callbackStr 'dc = ''b''; '];
callbackStr = [callbackStr ' figure(2)'];
uie = uicontrol('String', 'EDIT', 'Units', 'normalized' ...
     , 'Position', [0.92 0.62 0.08 0.05], 'CallBack', ...
   [rdr callbackStr]);

uiMA = uicontrol('String', 'MA', 'Units', 'normalized', ...
       'Position', [0.92 0.56 0.08 0.05], 'CallBack', ...
       'matrixEma = bdrwmath(matrixE);');
  
uiAUX = uicontrol('Style', 'text', 'Units', 'normalized' ...
     , 'HorizontalAlignment', 'left', 'BackgroundColor',[0.92 0.92 0.92] ...
     , 'Position', [0.91 0.235 0.09 0.26] ...
     , 'String', 'auxfilt.m');

uiEPSAUX = uicontrol('String', 'EPS', 'Units', 'normalized', ...
      'Position', [0.92 0.41 0.08 0.05], 'CallBack', ...
      ['fh2=figure(2);set(fh2,''Name'',' ddfre ...
      ');clf;whitebg(fh2,[1 1 1]);clear auxfilt;' ...
      'auxfilt(0,0,4,5,10);print -deps auxfilt.eps']);

uiVIEWAUX = uicontrol('String', 'view', 'Units', 'normalized' ...
     , 'Position', [0.92 0.355 0.08 0.05], 'CallBack'...
     ,['fh2=figure(2);clf;set(fh2,''Name'',' ...
     ddfr ');clear auxfilt;auxfilt(0,0,4,5,10);whitebg(fh2,[1 1 1])']);

uiOPENAUX = uicontrol('String', 'open', 'Units', 'normalized', ...  
         'Position', [0.92 0.3 0.08 0.05], 'CallBack', ...
         ['clf;[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);' ...
         'matrixE=bdrwload(x0,y0,dx,ds,F,Nx,Ny,matrixE);'...
         'bdrwredr(x0,y0,dx,ds,F,Nx,Ny,matrixE,dc);butdraw']);

uiEXAMPLES = uicontrol('Style', 'text', 'Units', 'normalized' ...
     , 'HorizontalAlignment', 'left', 'BackgroundColor',[0.92 0.92 0.92] ...
     , 'Position', [0.885 0.13 0.12 0.08] ...
     , 'String', 'examples');

uiex1 = uicontrol('String', '1', 'Units', 'normalized' ...
     , 'Position', [0.89 0.13 0.025 0.04], 'CallBack', ...
 ['fh2=figure(2);clf;set(fh2,''Name'',' ddfr1 ');example1(0,0,4,5,10)']);

uiex2 = uicontrol('String', '2', 'Units', 'normalized' ...
     , 'Position', [0.92 0.13 0.025 0.04], 'CallBack', ...
 ['fh2=figure(2);clf;set(fh2,''Name'',' ddfr2 ');example2(0,0,4,5,10)']);

uiex3 = uicontrol('String', '3', 'Units', 'normalized' ...
     , 'Position', [0.95 0.13 0.025 0.04], 'CallBack', ...
 ['fh2=figure(2);clf;set(fh2,''Name'',' ddfr3 ');example3(0,0,4,5,10)']);

uiex4 = uicontrol('String', '4', 'Units', 'normalized' ...
     , 'Position', [0.98 0.13 0.02 0.04], 'CallBack', ...
 ['fh2=figure(2);clf;set(fh2,''Name'',' ddfr4 ');example4(0,0,4,5,10)']);

uiDELETE = uicontrol('String', 'DELETE', 'Units', 'normalized' ...
     , 'Position', [0.89 0.07 0.11 0.05],'CallBack', ...
     [rdr ';[matrixE,matrixEdel]=bdelete(x0,y0,dx,ds,F,Nx,Ny,matrixE); title(''CLICK a button'')']);
  
uiUNDO = uicontrol('String', 'UNDO', 'Units', 'normalized' ...
     , 'Position', [0.89 0.01 0.11 0.05],'CallBack', ...
   [rdr ';[matrixE]=bundo(x0,y0,dx,ds,F,Nx,Ny,matrixE,matrixEdel); matrixEdel = [];' ...
        ' title(''CLICK a button'')']);
end

if  editString(1) == 0
 ui1 = uicontrol('String', 'redraw', 'Units', 'normalized', ...
      'Position', [0.91 0.86 0.09 0.05], 'CallBack', ...
      ['clf;[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);' ...
      'bdrwredr(x0,y0,dx,ds,F,Nx,Ny,matrixE,dc);butdraw']);
else
  callbackStr = ['clf;'];
  callbackStr = [callbackStr '[x,y]= drawgrid(x0,y0,dx,ds,F,Nx,Ny);'];
  callbackStr = [callbackStr 'bdrwredr(x0,y0,dx,ds,F,Nx,Ny,matrixE,dc);'];
  callbackStr = [callbackStr 'butdraw;'];
  callbackStr = [callbackStr 'set(gcf,''DefaultTextColor'',''r'');'];
  callbackStr = [callbackStr 'dc = ''r'';eval(matrixE(editString(2),:)); '];
  callbackStr = [callbackStr 'title(''GO TO Edit window'');'];
  callbackStr = [callbackStr 'set(gcf,''DefaultTextColor'',''k''); '];
  callbackStr = [callbackStr 'dc = ''b''; '];
  ui1 = uicontrol('String', 'redraw', 'Units', 'normalized', ...
      'Position', [0.91 0.88 0.09 0.05], 'CallBack', callbackStr);
end
  
uiSAVEAUX = uicontrol('String', 'save', 'Units', 'normalized', ...
         'Position', [0.92 0.245 0.08 0.05], ...
         'CallBack', 'bdrwsave(matrixE);');

uiSAVEAS = uicontrol('String', 'SAVE', 'Units', 'normalized' ...
     , 'Position', [0.92 0.68 0.08 0.05] ...
     , 'CallBack', 'bdrwsaas(matrixE);');
  
title('CLICK a button')
